// BorrowEmitter.cs

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace BorrowSafety;

internal static class BorrowEmitter
{
    private const string CommaSep = ", ";
    
    extension (StringBuilder sb)
    {
        public object? NextLine
        {
            set
            {
                switch (value)
                {
                    case string s: sb.AppendLine(s); return;
                    case null: sb.AppendLine(); return;
                    case object o: sb.AppendLine(o.ToString()); return;
                }
            }
        }
        
        public StringBuilder Tab4 => sb.Append("    ");
    }
        
    public static string Emit(INamedTypeSymbol type)
    {
        StringBuilder sb = new();
        string ns = type.ContainingNamespace.IsGlobalNamespace ? "BorrowSafety.Generated" : type.ContainingNamespace.ToDisplayString();
        string extensionClassName = BorrowGenerator.SafeName(type) + "_BorrowExtensions";
        string fullyQualifiedFormatTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        ImmutableArray<ITypeParameterSymbol> openTypeParameters = CollectOpenTypeParameters(type);
        string typeParameters = RenderTypeParameters(openTypeParameters);
        sb.NextLine = "// <auto-generated />";
        sb.NextLine = "#nullable enable";
        sb.NextLine = $"// {DateTime.Now:yyyy-MM-dd HH:mm:ss}";
        sb.NextLine = null;
        sb.NextLine = $"namespace {ns};";
        sb.NextLine = null;
        sb.NextLine = $"public static partial class {extensionClassName}";
        sb.NextLine = "{";
        sb.Tab4.NextLine = $"extension{typeParameters}(BorrowSafety.Borrow<{fullyQualifiedFormatTypeName}> borrow)";
        if (!openTypeParameters.IsEmpty)
            AppendConstraints(sb, openTypeParameters);
        sb.Tab4.NextLine = "{";
        foreach (ISymbol member in type.GetMembers())
        {
            if (member.IsStatic) continue; 
            switch (member)
            {
                case IPropertySymbol property: EmitProperty(sb, property); break;
                case IMethodSymbol method: EmitMethod(sb, method); break;
            }
        }
        sb.Tab4.NextLine = "}";
        sb.NextLine = "}";
        return sb.ToString();
    }
    
    private static void EmitProperty(StringBuilder sb, IPropertySymbol property)
    {
        if (property.DeclaredAccessibility != Accessibility.Public)
            return; 
        if (property.IsIndexer) 
            return;

        string propertyType = TypeRenderer.Render(property.Type);
        
        string propertyName = property.Name;
        switch (property.GetMethod is IMethodSymbol { DeclaredAccessibility: Accessibility.Public }, property.SetMethod is IMethodSymbol { IsInitOnly: false, DeclaredAccessibility: Accessibility.Public })
        {
            case (true, false):
                XmlRenderer.AppendXml(sb, property);
                sb.Tab4.Tab4.NextLine = $"public {propertyType} {propertyName} => borrow.Unlock_Unsafe().{propertyName};";
                sb.NextLine = null;
                return;
            case (true, true):
                XmlRenderer.AppendXml(sb, property);
                sb.Tab4.Tab4.NextLine = $"public {propertyType} {propertyName}";
                sb.Tab4.Tab4.NextLine = "{";
                sb.Tab4.Tab4.Tab4.NextLine = $"get => borrow.Unlock_Unsafe().{propertyName};";
                sb.Tab4.Tab4.Tab4.NextLine = $"set => borrow.Unlock_Unsafe().{propertyName} = value;";
                sb.Tab4.Tab4.NextLine = "}";
                sb.NextLine = null; 
                return; 
            case (false, true):
                XmlRenderer.AppendXml(sb, property);
                sb.Tab4.Tab4.NextLine = $"public {propertyType} {propertyName} {{ set => borrow.Unlock_Unsafe().{propertyName} = value; }}";
                sb.NextLine = null;
                return;
            default: 
                return;
        } 
         
    }
        
    private static void EmitMethod(StringBuilder sb, IMethodSymbol method)
    {
        if (method.MethodKind != MethodKind.Ordinary) return; // Stay away from weird stuff...
        
        if (method.DeclaredAccessibility != Accessibility.Public) return;
        
        if (method.Name == "Dispose") return;
        
        string returnType = TypeRenderer.Render(method.ReturnType);
        string typeParameters = RenderTypeParameters(method.TypeParameters);
        string parameters = string.Join(CommaSep, method.Parameters.Select(ParameterRenderer.Render));
        string arguments = string.Join(CommaSep, method.Parameters.Select(ParameterRenderer.RenderArgument));
        XmlRenderer.AppendXml(sb, method); sb.Tab4.Tab4.NextLine = $"public {returnType} {method.Name}{typeParameters}({parameters})";
        AppendConstraints(sb, method.TypeParameters);
        sb.Tab4.Tab4.NextLine = $"=> borrow.Unlock_Unsafe().{method.Name}{typeParameters}({arguments});";
        sb.NextLine = null;
    }
    
    private static string RenderTypeParameters(ImmutableArray<ITypeParameterSymbol> typeParameters) 
        => typeParameters.IsEmpty 
        ? ""
        : $"<{string.Join(CommaSep, typeParameters.Select(x => x.Name))}>"
        ;
        
    private static void AppendConstraints(StringBuilder sb, ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        foreach (ITypeParameterSymbol tp in typeParameters)
        {
            List<string> constraints = [];
            if (tp.HasReferenceTypeConstraint)
                constraints.Add("class");
            if (tp.HasValueTypeConstraint)
                constraints.Add("struct");
            if (tp.HasUnmanagedTypeConstraint)
                constraints.Add("unmanaged");
            if (tp.HasNotNullConstraint)
                constraints.Add("notnull");
            // TO DO: figure something out for the "default" constraint

            foreach (ITypeSymbol type in tp.ConstraintTypes)
                constraints.Add(TypeRenderer.Render(type));
                
            if (tp.HasConstructorConstraint)
                constraints.Add("new()");
                
            if (constraints.Count == 0)
                continue;
                
            sb.Tab4.Tab4.Tab4.NextLine = $"where {tp.Name} : {string.Join(CommaSep, constraints)}";
        }
    }

    private static ImmutableArray<ITypeParameterSymbol> CollectOpenTypeParameters(ITypeSymbol type)
    {
        HashSet<ITypeParameterSymbol> results = new(SymbolEqualityComparer.Default);

        Visit(type);

        return results.ToImmutableArray();

        void Visit(ITypeSymbol current)
        {
            switch (current)
            {
                case ITypeParameterSymbol tp:
                    results.Add(tp);
                    break;

                case INamedTypeSymbol nt:
                {
                    foreach (ITypeSymbol arg in nt.TypeArguments)
                        Visit(arg);

                    if (nt.ContainingType is not null)
                        Visit(nt.ContainingType);

                    break;
                }

                case IArrayTypeSymbol at:
                    Visit(at.ElementType);
                    break;

                case IPointerTypeSymbol pt:
                    Visit(pt.PointedAtType);
                    break;
            }
        }
    }
} 



